// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x53YSqYu9UQKZv7sZYfY6w
// Component: VAwcC_YmCU

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import YouTube from "@plasmicpkgs/react-youtube"; // plasmic-import: CHO21V9uYw/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: x53YSqYu9UQKZv7sZYfY6w/projectcss
import sty from "./PlasmicBodyContent.module.css"; // plasmic-import: VAwcC_YmCU/css

export type PlasmicBodyContent__VariantMembers = {};
export type PlasmicBodyContent__VariantsArgs = {};
type VariantPropType = keyof PlasmicBodyContent__VariantsArgs;
export const PlasmicBodyContent__VariantProps = new Array<VariantPropType>();

export type PlasmicBodyContent__ArgsType = {
  content?: any;
  onContentChange?: (val: any) => void;
  onTypeChange?: (val: any) => void;
};
type ArgPropType = keyof PlasmicBodyContent__ArgsType;
export const PlasmicBodyContent__ArgProps = new Array<ArgPropType>(
  "content",
  "onContentChange",
  "onTypeChange"
);

export type PlasmicBodyContent__OverridesType = {
  root?: p.Flex<"div">;
  text?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  youTube?: p.Flex<typeof YouTube>;
};

export interface DefaultBodyContentProps {
  content?: any;
  onContentChange?: (val: any) => void;
  onTypeChange?: (val: any) => void;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBodyContent__RenderFunc(props: {
  variants: PlasmicBodyContent__VariantsArgs;
  args: PlasmicBodyContent__ArgsType;
  overrides: PlasmicBodyContent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "type",
        type: "readonly",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          $state.content.type ?? $props.type,

        onChangeProp: "onTypeChange"
      },
      {
        path: "content",
        type: "writable",
        variableType: "object",

        valueProp: "content",
        onChangeProp: "onContentChange"
      }
    ],
    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root
        )}
      >
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          {"Title"}
        </div>
        {true ? (
          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"100%" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"100%" as const}
            loading={"lazy" as const}
            src={(() => {
              try {
                return $state.content.value;
              } catch (e) {
                if (e instanceof TypeError) {
                  return undefined;
                }
                throw e;
              }
            })()}
          />
        ) : null}
        {true ? (
          <YouTube
            data-plasmic-name={"youTube"}
            data-plasmic-override={overrides.youTube}
            className={classNames("__wab_instance", sty.youTube)}
            videoId={(() => {
              try {
                return $state.content.value;
              } catch (e) {
                if (e instanceof TypeError) {
                  return "R6MeLqRQzYw";
                }
                throw e;
              }
            })()}
          />
        ) : null}
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text", "img", "youTube"],
  text: ["text"],
  img: ["img"],
  youTube: ["youTube"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
  img: typeof p.PlasmicImg;
  youTube: typeof YouTube;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBodyContent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBodyContent__VariantsArgs;
    args?: PlasmicBodyContent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBodyContent__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBodyContent__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBodyContent__ArgProps,
          internalVariantPropNames: PlasmicBodyContent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBodyContent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBodyContent";
  } else {
    func.displayName = `PlasmicBodyContent.${nodeName}`;
  }
  return func;
}

export const PlasmicBodyContent = Object.assign(
  // Top-level PlasmicBodyContent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    img: makeNodeComponent("img"),
    youTube: makeNodeComponent("youTube"),

    // Metadata about props expected for PlasmicBodyContent
    internalVariantProps: PlasmicBodyContent__VariantProps,
    internalArgProps: PlasmicBodyContent__ArgProps
  }
);

export default PlasmicBodyContent;
/* prettier-ignore-end */
